# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'smart_life' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for smart_life
  pod 'SwiftyJSON'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'Alamofire', '~> 3.4'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
end
